services:
  - type: web
    name: house-price-predictor
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --chdir /app main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: PYTHONPATH
        value: /app
